# Generated by Django 6.1.1 on 2026-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatCurhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField(blank=True, null=True)),
                ('url_audio', models.URLField(blank=True, null=True)),
                ('emosi', models.CharField(blank=True, max_length=50, null=True)),
                ('akar_masalah', models.TextField(blank=True, null=True)),
                ('rekomendasi', models.TextField(blank=True, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
