# Generated by Django 6.1.1 on 2026-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatcurhat',
            name='url_audio',
        ),
        migrations.AddField(
            model_name='riwayatcurhat',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Diisi jika curhat via suara', null=True, upload_to='audio_curhat/'),
        ),
        migrations.AlterField(
            model_name='riwayatcurhat',
            name='emosi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatcurhat',
            name='teks',
            field=models.TextField(blank=True, help_text='Diisi jika curhat via teks', null=True),
        ),
    ]
