# Generated by Django 6.1.1 on 2026-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_riwayatcurhat_url_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatcurhat',
            name='audio_name',
            field=models.CharField(blank=True, help_text='Nama file audio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatcurhat',
            name='audio_file',
            field=models.BinaryField(blank=True, help_text='Data file audio', null=True),
        ),
    ]
